### ISSUE TITLE
Convert MediaWiki history into git commits

### ISSUE THREAD

**Issue by renoirb** [webplatform/docs#2]
We’ll attempt to import as much editions as MediaWiki dumpBackup XML can give us. 

No Wikitext syntax conversion into Markdown will be done there. We’ll do such conversion only at the latest version of each page.
 
## Tasks
* [x] Get MediaWiki page save revision author
* [x] Convert into a loop of git commits with `--author="John Doe <jdoe@example.org>`
* [x] "*runner*"; Loop through each page in dumpBackup XML, loop for each revision, commit

**Comment by renoirb** [comment]
[/] Adressed in this PHP class [Revision.php](https://github.com/webplatform/mediawiki-transformer/blob/master/lib/WebPlatform/MediaWiki/Transformer/Model/Revision.php).

**Comment by renoirb** [comment]
We have full history!  We now need to filter latest revision and a minimal static-site generator to render the content.

**Comment by renoirb** [comment]
Duplicate of webplatform/mediawiki-conversion/issues/4
